import streamlit as st

LANG = {
    "tr": {
        "title": "DocuMind",
        "tagline": "Dokümanlarınla konuş",
        "upload_header": "Dosya Yükle",
        "upload_label": "PDF, DOCX veya TXT",
        "upload_btn": "Yükle",
        "uploading": "Yükleniyor…",
        "upload_success": "yüklendi",
        "upload_error": "Yükleme hatası",
        "upload_empty": "Lütfen bir dosya seçin.",
        "upload_too_big": "Dosya çok büyük (max 50 MB).",
        "docs_header": "Dokümanlar",
        "docs_empty": "Henüz doküman yok.",
        "active": "Aktif",
        "passive": "Pasif",
        "toggle_btn": "Aç/Kapat",
        "delete_btn": "Sil",
        "preview_btn": "Önizle",
        "close": "Kapat",
        "chat_header": "Sohbet",
        "chat_placeholder": "Bir soru yazın…",
        "ask_btn": "Gönder",
        "asking": "Yanıt aranıyor…",
        "sources": "Kaynaklar",
        "chunks_label": "İlgili parçalar",
        "no_docs": "⚠️ Önce bir doküman yükleyin.",
        "summarize_header": "Özet Al",
        "summarize_btn": "Özetle",
        "summarizing": "Özetleniyor…",
        "summarize_q": "Bu dokümanın tüm içeriğini kapsamlı şekilde özetle. Ana başlıkları, önemli bilgileri ve çıkarımları belirt.",
        "select_docs": "Arama yapılacak dokümanlar",
        "select_docs_hint": "Boş bırakılırsa hepsi aranır",
        "top_k": "Kullanılacak parça sayısı",
        "api_error": "Backend'e bağlanılamadı. Sunucunun çalıştığından emin ol.",
        "chunks_count": "parça",
        "lang_label": "Dil / Language",
        "export_btn": "Sohbeti Dışa Aktar",
        "clear_btn": "Sohbeti Temizle",
        "settings": "Arama Ayarları",
        "you": "Siz",
        "ai": "DocuMind",
        "chunk_from": "Kaynak",
        "chunk_id": "Parça",
        "score": "Skor",
        "gen_suggestions": "Yeni sorular üret",
        "gen_suggestions_spinner": "Öneri üretiliyor…",
        "suggestions_title": "Bu doküman için önerilen sorular",
        "select_doc_for_suggestions": "Doküman seçin",
        "stats_total": "Toplam Doküman",
        "stats_chunks": "Toplam Parça",
        "stats_active": "Aktif",
        "lang_instruction": "Cevabını Türkçe ver.",
        "sug_prompt": (
            "Bu doküman hakkında kullanıcının sorabileceği, içerikle doğrudan ilgili "
            "3 farklı ve özgün soru üret. Soruları Türkçe yaz. "
            "Sadece soruları listele, başka hiçbir şey yazma. "
            "Her soruyu ayrı satıra yaz, numara veya tire kullanma."
        ),
    },
    "en": {
        "title": "DocuMind",
        "tagline": "Chat with your documents",
        "upload_header": "Upload File",
        "upload_label": "PDF, DOCX or TXT",
        "upload_btn": "Upload",
        "uploading": "Uploading…",
        "upload_success": "uploaded",
        "upload_error": "Upload error",
        "upload_empty": "Please select a file.",
        "upload_too_big": "File too large (max 50 MB).",
        "docs_header": "Documents",
        "docs_empty": "No documents yet.",
        "active": "Active",
        "passive": "Paused",
        "toggle_btn": "Toggle",
        "delete_btn": "Delete",
        "preview_btn": "Preview",
        "close": "Close",
        "chat_header": "Chat",
        "chat_placeholder": "Type a question…",
        "ask_btn": "Send",
        "asking": "Searching…",
        "sources": "Sources",
        "chunks_label": "Relevant chunks",
        "no_docs": "⚠️ Upload a document first.",
        "summarize_header": "Summarize",
        "summarize_btn": "Summarize",
        "summarizing": "Summarizing…",
        "summarize_q": "Give a comprehensive summary of this document. Include main topics, key information and conclusions.",
        "select_docs": "Documents to search",
        "select_docs_hint": "Leave empty to search all",
        "top_k": "Chunks to use",
        "api_error": "Cannot connect to backend. Make sure the server is running.",
        "chunks_count": "chunks",
        "lang_label": "Dil / Language",
        "export_btn": "Export Chat",
        "clear_btn": "Clear Chat",
        "settings": "Search Settings",
        "you": "You",
        "ai": "DocuMind",
        "chunk_from": "Source",
        "chunk_id": "Chunk",
        "score": "Score",
        "gen_suggestions": "Generate new questions",
        "gen_suggestions_spinner": "Generating suggestions…",
        "suggestions_title": "Suggested questions for this document",
        "select_doc_for_suggestions": "Select document",
        "stats_total": "Total Docs",
        "stats_chunks": "Total Chunks",
        "stats_active": "Active",
        "lang_instruction": "Answer in English.",
        "sug_prompt": (
            "Generate 3 specific, insightful questions a user might ask about this document. "
            "Write the questions in English. "
            "Only list the questions, nothing else. Each question on a new line, no numbers or dashes."
        ),
    },
}


def t(key: str) -> str:
    return LANG[st.session_state.lang].get(key, key)
